# frozen_string_literal: true
source "https://rubygems.org"

gem "activesupport"
gem "auto_paragraph"
gem "babosa"
gem "erubis"
gem "kramdown"
gem "nanoc", "~> 4.9"
gem "new_base_60"
gem "nokogiri"
gem "sass"
gem "slim"
gem "tilt"
gem "unicode"
